version: '2'
services:
  broker2:
    # build:
    #   context: ./broker
    image: iotdsa/broker-scala:0.4.0-SNAPSHOT
    container_name: broker2
    environment:
      JAVA_OPTS: "-agentlib:jdwp=transport=dt_socket,address=9005,server=y,suspend=n"
      STATSD_HOST: graphana
      STATSD_PORT: 8125
      ZIPKIN_HOST: zipkin
      ZIPKIN_PORT: 9411
      AKKA_REMOTING_BIND_HOST: broker2
      AKKA_REMOTING_BIND_PORT: 2551
      AKKA_SEED_NODES: broker1:2551,broker2:2551
      AKKA_ACTOR_SYSTEM_NAME: DSASystem
    ports:
      - "9000:9000"
      - "9005:9005"
      - "2551:2551"
      - "9443:9443"
    networks:
      - dsnet
    links:
      - graphana
    depends_on:
      - graphana
      - zipkin
  broker1:
    # build:
    #   context: ./broker
    image: iotdsa/broker-scala:0.4.0-SNAPSHOT
    container_name: broker1
    environment:
      JAVA_OPTS: "-agentlib:jdwp=transport=dt_socket,address=9005,server=y,suspend=n"
      STATSD_HOST: graphana
      STATSD_PORT: 8125
      ZIPKIN_HOST: zipkin
      ZIPKIN_PORT: 9411
      AKKA_REMOTING_BIND_HOST: broker1
      AKKA_REMOTING_BIND_PORT: 2551
      AKKA_SEED_NODES: broker1:2551,broker2:2551
      AKKA_ACTOR_SYSTEM_NAME: DSASystem
    ports:
      - "9010:9000"
      - "9015:9005"
      - "2552:2551"
      - "9453:9443"
    networks:
      - dsnet
    links:
      - graphana
    depends_on:
      - graphana
      - zipkin
  shell:
    build: 
      context: ./shell-dslink
    image: shell-dslink:latest
    stdin_open: true
    tty: true
    container_name: shell-dslink
    environment:
      BROKER_HOST: broker1
      BROKER_PORT: 9000
    depends_on:
      - broker1
    links:
      - broker1
    networks:
      - dsnet

  weather:
    build: 
      context: ./weather-dslink
    image: weather-dslink:latest
    container_name: weather-dslink
    environment:
      BROKER_HOST: broker2
      BROKER_PORT: 9000
    depends_on:
      - broker2
    links:
      - broker2
    networks:
      - dsnet

#  mysql:
#    image: openzipkin/zipkin-mysql
#    container_name: mysql
#    networks:
#      - dsnet
    # Uncomment to expose the storage port for testing
    # ports:
    #   - 3306:3306

  # The zipkin process services the UI, and also exposes a POST endpoint that
  # instrumentation can send trace data to. Scribe is disabled by default.
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    # Environment settings are defined here https://github.com/openzipkin/zipkin/tree/1.19.0/zipkin-server#environment-variables
#    environment:
#      - STORAGE_TYPE=mysql
#      # Point the zipkin at the storage backend
#      - MYSQL_HOST=mysql
#      # Uncomment to enable scribe
#      # - SCRIBE_ENABLED=true
#      # Uncomment to enable self-tracing
#      # - SELF_TRACING_ENABLED=true
#      # Uncomment to enable debug logging
#      - JAVA_OPTS=-Dlogging.level.zipkin=DEBUG -Dlogging.level.zipkin2=DEBUG
    ports:
      # Port used for the Zipkin UI and HTTP Api
      - 9411:9411
      # Uncomment if you set SCRIBE_ENABLED=true
      # - 9410:9410
#    depends_on:
#      - mysql
    networks:
      - dsnet

  system:
    build: 
      context: ./system
    image: system-dslink:latest
    container_name: system-dslink
    environment:
      BROKER_HOST: broker2
      BROKER_PORT: 9000
    depends_on:
      - broker2
    links:
      - broker2
    networks:
      - dsnet

  graphana:
    build:
      context: ./graphana
    ports:
      - "9680:80"
      - "9681:81"
      - "2003:2003"
      - "8125:8125/udp"
      - "8126:8126"
    networks:
      - dsnet

networks:
  dsnet:
    external:
      name:  automation_dsnet
