#!/usr/bin/env bash

VERSION="0.3.1"

PORTS="--net dsa -p 9000:9000"
VOLUMES="-v $PWD/conf:/opt/docker/conf -v /opt/geolite:/opt/docker/geolite"

docker run -d --name dsa-broker $PORTS $VOLUMES iotdsa/broker-scala:$VERSION

