#!/usr/bin/env bash

if [ -z "$1" ] || [ -z "$2" ]
  then
    echo "Usage: start_frontend <name> <port>. Eg. 'start_frontend frontend 9000'"
    exit -1
fi

VERSION="0.4.0-SNAPSHOT"

VOLUMES="-v $PWD/conf:/opt/docker/conf -v /opt/geolite:/opt/docker/geolite"
NETWORK="--net dsa -h $1 -p $2:9000 -e HOST=$1"
APP_ARGS="-Dconfig.file=/opt/docker/conf/frontend.conf"

docker run -d --name $1 $VOLUMES $NETWORK iotdsa/broker-scala:$VERSION $APP_ARGS
