#!/usr/bin/env bash

if [ -z "$1" ] || [ -z "$2" ]
  then
    echo "Usage: start_backend <name> <port>. Eg. 'start_backend backend01 2551'"
    exit -1
fi

VERSION="0.4.0-SNAPSHOT"

VOLUMES="-v $PWD/conf:/opt/docker/conf -v /opt/geolite:/opt/docker/geolite"
NETWORK="--net dsa -h $1 -p $2:2551 -e HOST=$1"
APP_ARGS="-main models.akka.cluster.BrokerBackend -Dconfig.file=/opt/docker/conf/backend.conf 2551"

docker run -d --name $1 $NETWORK $VOLUMES iotdsa/broker-scala:$VERSION $APP_ARGS
