---
galaxy_info:
  author: Andrew Rothstein
  description: installs minikube
  company: BlackRock
  license:
    - MIT
  min_ansible_version: 2.4
  platforms:
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: Alpine
      versions:
        - all
    - name: Archlinux
      versions:
        - all
    - name: Debian
      versions:
        - jessie
        - stretch
  galaxy_tags:
    - k8s
    - virtualization

dependencies:
  - role: andrewrothstein.kubectl
    version: v1.1.9
