---
galaxy_info:
  author: Paul Durivage
  description: A comprehensive and (ideally) sane way to install Docker on Ubuntu 12.04+
  license: Apache v2.0
  min_ansible_version: 2.2
  platforms:
    - name: Debian
      versions:
        - jessie
    - name: Ubuntu
      versions:
        - precise
        - trusty
        - xenial
  categories:
    - development
    - packaging
    - system
dependencies: []
  # List your role dependencies here, one per line. Only
  # dependencies available via galaxy should be listed here.
  # Be sure to remove the '[]' above if you add dependencies
  # to this list.
  
