package models.bench

import scala.concurrent.duration.{ DurationInt, FiniteDuration }

import org.joda.time.{ DateTime, Interval }

import BenchmarkResponder.{ BenchmarkResponderConfig, RspStatsSample }
import akka.actor.{ ActorRef, Props }
import models.RequestEnvelope
import models.akka.{ CommProxy, DSLinkMode, RegexContext }
import models.rpc._

/**
 * Simulates a responder which contains:
 * - a fixed number of nodes named "data0", "data1", etc. each storing a Number value, initially 0
 * - action "incCounter" on each node, which increments the node's value
 * - action "resetCounter" on each node, which sets the node's value back to 0
 */
class BenchmarkResponder(linkName: String, proxy: CommProxy, config: BenchmarkResponderConfig)
  extends AbstractEndpointActor(linkName, DSLinkMode.Responder, proxy, config) {

  private val data = Array.fill(config.nodeCount)(0)
  private val subscriptions = collection.mutable.Map.empty[String, Int]

  private var lastReported: RspStatsSample = _
  private var invokesRcvd = 0
  private var updatesSent = 0

  override def preStart() = {
    super.preStart

    lastReported = RspStatsSample(linkName, new Interval(DateTime.now, DateTime.now), 0, 0)
  }

  override def receive = super.receive orElse {
    case msg @ RequestEnvelope(requests) =>
      log.debug("[{}]: received {}", linkName, msg)
      requests foreach processRequest

    case msg => log.warning("[{}]: received unknown message - {}", linkName, msg)
  }

  private def processRequest: PartialFunction[DSARequest, Unit] = {
    case SubscribeRequest(rid, paths) =>
      paths foreach { path =>
        subscriptions += path.path -> path.sid
      }
      sender ! emptyResponseMessage(rid)

    case UnsubscribeRequest(rid, sids) =>
      val keys = subscriptions.collect {
        case (path, sid) if sids.contains(sid) => path
      }
      subscriptions --= keys
      sender ! emptyResponseMessage(rid)

    case req: InvokeRequest => processInvokeRequest(req)
  }

  private def processInvokeRequest(req: InvokeRequest) = req.path match {
    case r"/data(\d+)$index/incCounter" =>
      replyToInvoke(req)
      incCounter(index.toInt)
    case r"/data(\d+)$index/resetCounter" =>
      replyToInvoke(req)
      resetCounter(index.toInt)
  }

  private def incCounter(index: Int) = {
    data(index - 1) += 1
    notifySubs(index)
  }

  private def resetCounter(index: Int) = {
    data(index - 1) = 0
    notifySubs(index)
  }

  private def replyToInvoke(req: InvokeRequest) = {
    invokesRcvd += 1
    sender ! emptyResponseMessage(req.rid)
  }

  private def notifySubs(index: Int) = subscriptions.get("/data" + index) foreach { sid =>
    val update = DSAValue.obj("sid" -> sid, "value" -> data(index - 1), "ts" -> DateTime.now.toString)
    proxy ! ResponseMessage(localMsgId.inc, None, List(DSAResponse(0, Some(StreamState.Open), Some(List(update)))))
    updatesSent += 1
  }

  private def emptyResponseMessage(rid: Int) =
    ResponseMessage(localMsgId.inc, None, List(DSAResponse(rid, Some(StreamState.Closed))))

  protected def reportStats() = {
    val interval = new Interval(lastReported.interval.getEnd, DateTime.now)
    val stats = RspStatsSample(linkName, interval, invokesRcvd - lastReported.invokesRcvd,
      updatesSent - lastReported.updatesSent)
    log.debug("[{}]: collected {}", linkName, stats)
    config.statsCollector foreach (_ ! stats)
    lastReported = stats
  }
}

/**
 * Factory for [[BenchmarkResponder]].
 */
object BenchmarkResponder {
  import AbstractEndpointActor._

  /**
   * BenchmarkResponder configuration.
   */
  case class BenchmarkResponderConfig(nodeCount: Int, statsInterval: FiniteDuration = 5 seconds,
                                      statsCollector: Option[ActorRef] = None) extends EndpointConfig

  /**
   * Creates a new instance of BenchmarkResponder props.
   */
  def props(linkName: String, proxy: CommProxy, config: BenchmarkResponderConfig) =
    Props(new BenchmarkResponder(linkName, proxy, config))

  /**
   * Stats generated by the responder, sent to the stats collector.
   */
  case class RspStatsSample(id: String, interval: Interval, invokesRcvd: Int, updatesSent: Int)
    extends RspStatsBehavior { val duration = interval.toDuration }
}