#!/usr/bin/env bash
KAFKA_HOME=/usr/local/Cellar/kafka/0.10.1.0

$KAFKA_HOME/bin/kafka-streams-application-reset --application-id $1 --intermediate-topics $1_REQ_ENVELOPE_IN,$1_RSP_ENVELOPE_IN
rm -rf /tmp/broker
